targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/data/graphql/schema.graphql
              queries_glob: lib/data/graphql/query/get_all_tasks.graphql
              output: lib/data/graphql/query/get_all_tasks.dart
            - schema: lib/data/graphql/schema.graphql
              queries_glob: lib/data/graphql/mutation/create_task.graphql
              output: lib/data/graphql/mutation/create_task.dart
            - schema: lib/data/graphql/schema.graphql
              queries_glob: lib/data/graphql/mutation/update_task.graphql
              output: lib/data/graphql/mutation/update_task.dart
